### ISSUE TITLE
英文推理报错

### ISSUE THREAD

**Issue by hanswang73** [baichuan-inc/Baichuan-13B#129]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/generation/utils.py", line 2678, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

transformer == 4.31.0
刚下载的最新的模型文件
prompt = “Do you know ifax ?”   (其它的英文提问也出类似报错)

**Comment by jameswu2014** [comment]
你测试的平台是啥，代码能不能贴全一点

**Comment by minguo** [comment]
用load_in_8bit加载，问"你是谁"就会报这个错

**Comment by jameswu2014** [comment]
> 用load_in_8bit加载，问"你是谁"就会报这个错

你可以尝试用量化接口quantizer试试，具体可参考ReadMe

**Comment by minguo** [comment]
我就是不能在线量化，因为我的显存只有24G，这个模型需要全部加载，我的卡加载不了，如果可以加载我也不需要做量化了

**Comment by minguo** [comment]
还有，readme上说有量化好的int8模型，那个地址都失效了，希望可以再次开放int8模型的下载，这样24G显存的卡就不用那么纠结了

**Comment by minguo** [comment]
> > 用load_in_8bit加载，问"你是谁"就会报这个错
> 
> 你可以尝试用量化接口quantizer试试，具体可参考ReadMe

我就是不能在线量化，因为我的显存只有24G，这个模型需要全部加载，我的卡加载不了，如果可以加载我也不需要做量化了

**Comment by minguo** [comment]
> > 用load_in_8bit加载，问"你是谁"就会报这个错
> 
> 你可以尝试用量化接口quantizer试试，具体可参考ReadMe

还有，readme上说有量化好的int8模型，那个地址都失效了，希望可以再次开放int8模型的下载，这样24G显存的卡就不用那么纠结了

**Comment by jameswu2014** [comment]
> > > 用load_in_8bit加载，问"你是谁"就会报这个错
> > 
> > 
> > 你可以尝试用量化接口quantizer试试，具体可参考ReadMe
> 
> 我就是不能在线量化，因为我的显存只有24G，这个模型需要全部加载，我的卡加载不了，如果可以加载我也不需要做量化了

在线量化不需要显存24G的，在线量化会把结果先加载到内存里，量化后再copy到显存里。你看看量化那部分的说明，去掉device_map='auto'去掉

**Comment by jameswu2014** [comment]
> 用load_in_8bit加载，问"你是谁"就会报这个错

我试了下load_in_8bit,我这边是没问题的。你可以把你的所有代码都贴出来，我看看能不能复现？另外，你的平台是什么？3090？

**Comment by minguo** [comment]
> > 用load_in_8bit加载，问"你是谁"就会报这个错
> 
> 我试了下load_in_8bit,我这边是没问题的。你可以把你的所有代码都贴出来，我看看能不能复现？另外，你的平台是什么？3090？

    model = AutoModelForCausalLM.from_pretrained(
        "baichuan-inc/Baichuan-13B-Chat",
        load_in_8bit=True,
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    
    我只改动了你web_demo.py里的这理，就是加了load_in_8bit=True,这行，用P40的卡去跑，ubuntu20.04系统

**Comment by jameswu2014** [comment]
> > > 用load_in_8bit加载，问"你是谁"就会报这个错
> > 
> > 
> > 我试了下load_in_8bit,我这边是没问题的。你可以把你的所有代码都贴出来，我看看能不能复现？另外，你的平台是什么？3090？
> 
> ```
> model = AutoModelForCausalLM.from_pretrained(
>     "baichuan-inc/Baichuan-13B-Chat",
>     load_in_8bit=True,
>     torch_dtype=torch.float16,
>     device_map="auto",
>     trust_remote_code=True
> )
> 
> 我只改动了你web_demo.py里的这理，就是加了load_in_8bit=True,这行，用P40的卡去跑，ubuntu20.04系统
> ```

我没有在P40上跑过

**Comment by hanswang73** [comment]
我之前用load_in_8bit，频繁报这个错误，包括最开始的那个可复现bug的英文prompt

后来改为fp16，bug频率大幅下降，但还是有

**Comment by XiaoBin1992** [comment]
> > > 用load_in_8bit加载，问"你是谁"就会报这个错
> > 
> > 
> > 我试了下load_in_8bit,我这边是没问题的。你可以把你的所有代码都贴出来，我看看能不能复现？另外，你的平台是什么？3090？
> 
> ```
> model = AutoModelForCausalLM.from_pretrained(
>     "baichuan-inc/Baichuan-13B-Chat",
>     load_in_8bit=True,
>     torch_dtype=torch.float16,
>     device_map="auto",
>     trust_remote_code=True
> )
> 
> 我只改动了你web_demo.py里的这理，就是加了load_in_8bit=True,这行，用P40的卡去跑，ubuntu20.04系统
> ```

我在测试环境复现的时候，当调用多次.cuda()，会出现这个问题，原因是bitsandbytes中 cuda会执行量化操作，导致值域变化，出现inf，随后导致nan。

**Comment by XiaoBin1992** [comment]
> 我之前用load_in_8bit，频繁报这个错误，包括最开始的那个可复现bug的英文prompt
> 
> 后来改为fp16，bug频率大幅下降，但还是有

@hanswang73 意思是说，load_in_8bit+bf16 比 load_in_8bit+fp16 更容易出bug？
