### ISSUE TITLE
Baichuan 13B 全参微调时命令报错

### ISSUE THREAD

**Issue by tanglu86** [baichuan-inc/Baichuan-13B#148]
deep_speed.json 配置内容
```
{
  "train_micro_batch_size_per_gpu": "auto",
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "initial_scale_power": 16, 
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },  
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "overlap_comm": false,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "contiguous_gradients" : true
  }
}
```

执行的命令
```
deepspeed --num_gpus=4 src/train_bash.py \
--stage sft \
--model_name_or_path /data/LLM_Project/Baichuan-13B-Chat \
--lora_target W_pack \
--template baichuan \
--do_train \
--dataset xiaogang2 \
--finetuning_type full \
--output_dir /data/LLM_OUTPUT_Project/Baichuan-13B-Chat-deepspeed \
--overwrite_cache \
--per_device_train_batch_size 4 \
--per_device_eval_batch_size 4 \
--gradient_accumulation_steps 8 \
--preprocessing_num_workers 16 \
--lr_scheduler_type cosine \
--logging_steps 10 \
--save_steps 100 \
--eval_steps 100 \
--learning_rate 5e-5 \
--max_grad_norm 0.5 \
--num_train_epochs 2.0 \
--dev_ratio 0.01 \
--evaluation_strategy steps \
--load_best_model_at_end \
--plot_loss \
--fp16 \
--deepspeed deepspeed.json
```

报错内容：
```
Traceback (most recent call last):
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (13) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 14, in <module>
    main()
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 5, in main
    run_exp()
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/tune.py", line 20, in run_exp
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = get_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 81, in get_train_args
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = parse_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 51, in parse_train_args
    return _parse_args(parser, args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 30, in _parse_args
    return parser.parse_args_into_dataclasses()
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 117, in __init__
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/training_args.py", line 1607, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 76, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 66, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
Traceback (most recent call last):
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: deepspeed.json
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (13) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 14, in <module>
    main()
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 5, in main
    run_exp()
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/tune.py", line 20, in run_exp
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = get_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 81, in get_train_args
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = parse_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 51, in parse_train_args
    return _parse_args(parser, args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 30, in _parse_args
    return parser.parse_args_into_dataclasses()
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 117, in __init__
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/training_args.py", line 1607, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 76, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 66, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: deepspeed.json
Traceback (most recent call last):
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (13) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 14, in <module>
    main()
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 5, in main
    run_exp()
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/tune.py", line 20, in run_exp
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = get_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 81, in get_train_args
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = parse_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 51, in parse_train_args
    return _parse_args(parser, args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 30, in _parse_args
    return parser.parse_args_into_dataclasses()
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 117, in __init__
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/training_args.py", line 1607, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 76, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 66, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: deepspeed.json
Traceback (most recent call last):
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 52, in __init__
    config_decoded = base64.urlsafe_b64decode(config_file_or_dict).decode("utf-8")
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (13) cannot be 1 more than a multiple of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 14, in <module>
    main()
  File "/data/LLaMA-Efficient-Tuning-main/src/train_bash.py", line 5, in main
    run_exp()
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/tune.py", line 20, in run_exp
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = get_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 81, in get_train_args
    model_args, data_args, training_args, finetuning_args, generating_args, general_args = parse_train_args(args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 51, in parse_train_args
    return _parse_args(parser, args)
  File "/data/LLaMA-Efficient-Tuning-main/src/llmtuner/tuner/core/parser.py", line 30, in _parse_args
    return parser.parse_args_into_dataclasses()
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 117, in __init__
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/training_args.py", line 1607, in __post_init__
    self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 76, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/transformers/deepspeed.py", line 66, in __init__
    super().__init__(config_file_or_dict)
  File "/data/miniconda3/envs/llama_etuning/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 55, in __init__
    raise ValueError(
ValueError: Expected a string path to an existing deepspeed config, or a dictionary, or a base64 encoded string. Received: deepspeed.json
[2023-08-18 16:11:18,772] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 126956
[2023-08-18 16:11:18,848] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 126957
[2023-08-18 16:11:18,867] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 126958
[2023-08-18 16:11:18,877] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 126959
[2023-08-18 16:11:18,877] [ERROR] [launch.py:321:sigkill_handler] ['/data/miniconda3/envs/llama_etuning/bin/python', '-u', 'src/train_bash.py', '--local_rank=3', '--stage', 'sft', '--model_name_or_path', '/data/LLM_Project/Baichuan-13B-Chat', '--lora_target', 'W_pack', '--template', 'baichuan', '--do_train', '--dataset', 'xiaogang2', '--finetuning_type', 'full', '--output_dir', '/data/LLM_OUTPUT_Project/Baichuan-13B-Chat-deepspeed', '--overwrite_cache', '--per_device_train_batch_size', '4', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '8', '--preprocessing_num_workers', '16', '--lr_scheduler_type', 'cosine', '--logging_steps', '10', '--save_steps', '100', '--eval_steps', '100', '--learning_rate', '5e-5', '--max_grad_norm', '0.5', '--num_train_epochs', '2.0', '--dev_ratio', '0.01', '--evaluation_strategy', 'steps', '--load_best_model_at_end', '--plot_loss', '--fp16', '--deepspeed', 'deepspeed.json'] exits with return code = 1
```

**Comment by hiyouga** [comment]
See https://github.com/hiyouga/LLaMA-Efficient-Tuning/issues/573#issuecomment-1683552631

**Comment by tanglu86** [comment]
我的问题，--deepspeed指定的文件名和本地文件名不一致
