### ISSUE TITLE
有人在macbook pro 16GB上跑过百川13B吗？

### ISSUE THREAD

**Issue by mosthandsomeman** [baichuan-inc/Baichuan-13B#165]
Traceback (most recent call last):
  File "/Users/mfz/workplace/Baichuan-13B/web_demo.py", line 77, in <module>
    main()
  File "/Users/mfz/workplace/Baichuan-13B/web_demo.py", line 56, in main
    model, tokenizer = init_model()
  File "/Users/mfz/workplace/Baichuan-13B/venv/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/Users/mfz/workplace/Baichuan-13B/venv/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/Users/mfz/workplace/Baichuan-13B/venv/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/Users/mfz/workplace/Baichuan-13B/venv/lib/python3.9/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/Users/mfz/workplace/Baichuan-13B/web_demo.py", line 24, in init_model
    model = model.quantize(4).to('mps')
  File "/Users/mfz/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/modeling_baichuan.py", line 530, in quantize
    layer.self_attn.W_pack = QLinear(
  File "/Users/mfz/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/quantizer.py", line 99, in __init__
    self.weight = quant4(weight, self.scale)
  File "/Users/mfz/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Chat/quantizer.py", line 41, in quant4
    stream = torch.cuda.current_stream()
  File "/Users/mfz/workplace/Baichuan-13B/venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 713, in current_stream
    _lazy_init()
  File "/Users/mfz/workplace/Baichuan-13B/venv/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

mac上cuda改成to.("mps")
代码中包含cuda的代码应该怎么改

**Comment by catdiscus** [comment]
可以试试[text-generation-webui](https://github.com/oobabooga/text-generation-webui)  我本地用这个启动模型无问题
