### ISSUE TITLE
一台机器有2张RTX3060显卡，跑官方web_demo的时候报了异常

### ISSUE THREAD

**Issue by youyajike** [baichuan-inc/Baichuan-13B#171]
操作系统：Ubuntu 22.04
Python:3.10
Cuda:12.0

2023-08-31 17:34:19.766 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 311, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/root/Baichuan-13B-main/web_demo.py", line 73, in <module>
    main()
  File "/root/Baichuan-13B-main/web_demo.py", line 52, in main
    model, tokenizer = init_model()
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 211, in wrapper
    return cached_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 240, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 266, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/root/Baichuan-13B-main/web_demo.py", line 14, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 511, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3049, in from_pretrained
    if resolved_archive_file.endswith(".index"):
AttributeError: 'list' object has no attribute 'endswith'

**Comment by forcemeter** [comment]
可以尝试用 FastChat 的 web 版本
