### ISSUE TITLE
cannot import name 'AutoModelForCausalLM' from 'transformers' 

### ISSUE THREAD

**Issue by shijunbao** [baichuan-inc/Baichuan-13B#20]
CONDA创建的虚拟环境，安装pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pyton3.11
requirements.txt安装完毕
运行web demo  报错：

2023-07-11 20:22:09.863 Uncaught app exception
Traceback (most recent call last):
  File "E:\tools\anaconda202304\envs\baichuan\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "J:\baichuan\web_demo.py", line 4, in <module>
    from transformers import AutoModelForCausalLM, AutoTokenizer
ImportError: cannot import name 'AutoModelForCausalLM' from 'transformers' (E:\tools\anaconda202304\envs\baichuan\Lib\site-packages\transformers\__init__.py)

**Comment by GradientGuru** [comment]
没有安装transformers
