### ISSUE TITLE
 make sure you have `safetensors` installed if the model you are using offers the weights in this format.

### ISSUE THREAD

**Issue by jerry-mengbo** [baichuan-inc/Baichuan-13B#64]
C:\Users\Administrator\Desktop\yolo\Baichuan-13B>python cli_demo.py
init model ...
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\yolo\Baichuan-13B\cli_demo.py", line 76, in <module>
    main()
  File "C:\Users\Administrator\Desktop\yolo\Baichuan-13B\cli_demo.py", line 38, in main
    model, tokenizer = init_model()
  File "C:\Users\Administrator\Desktop\yolo\Baichuan-13B\cli_demo.py", line 11, in init_model
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_f
actory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py"
, line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py"
, line 2980, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alt
ernatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

**Comment by jerry-mengbo** [comment]
哪位大神能帮忙看下这个问题
ValueError: The current device_map had weights offloaded to the disk. Please provide an offload_folder for them. Alt
ernatively, make sure you have safetensors installed if the model you are using offers the weights in this format.

**Comment by GradientGuru** [comment]
是否忘记下载或者没有下载完 safetensors 权重文件
