### ISSUE TITLE
cli_demo.py 切换Baichuan-13B-Chat 问答异常

### ISSUE THREAD

**Issue by xuxiaosheng0909** [baichuan-inc/Baichuan-13B#66]
切换代码：
model = AutoModelForCausalLM.from_pretrained(
        "baichuan-inc/Baichuan-13B-Chat",
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    ).half().to('mps')
    model.generation_config = GenerationConfig.from_pretrained(
        "baichuan-inc/Baichuan-13B-Chat"
    )
    tokenizer = AutoTokenizer.from_pretrained(
        "baichuan-inc/Baichuan-13B-Chat",
        use_fast=False,
        trust_remote_code=True
    )

异常信息：
欢迎使用百川大模型，输入进行对话，clear 清空历史，CTRL+C 中断生成，steam 开关流式生成，exit 结束。

用户：你好

Baichuan：Traceback (most recent call last):
  File "/root/Baichuan-13B/cli_demo_base.py", line 72, in <module>
    main()
  File "/root/Baichuan-13B/cli_demo_base.py", line 57, in main
    for response in model.chat(tokenizer, messages, stream=True):
  File "/root/envs/baichuan13b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Base/modeling_baichuan.py", line 536, in chat
    input_ids = self._build_chat_input(tokenizer, messages, generation_config.max_new_tokens)
  File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Base/modeling_baichuan.py", line 504, in _build_chat_input
    max_input_tokens = self.config.model_max_length - max_new_tokens
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType' 

请帮忙看下是什么原因

**Comment by xuxiaosheng0909** [comment]
def init_model():
    print("init model ...")
    model = AutoModelForCausalLM.from_pretrained(
        "baichuan-inc/Baichuan-13B-Base",
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    model.generation_config = GenerationConfig.from_pretrained(
        "baichuan-inc/Baichuan-13B-Base"
    )
    tokenizer = AutoTokenizer.from_pretrained(
        "baichuan-inc/Baichuan-13B-Base",
        use_fast=False,
        trust_remote_code=True
    )
    return model, tokenizer
